spring.application.name=backend

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://root:root@skillsync.buf804c.mongodb.net/?retryWrites=true&w=majority&appName=Skillsync
spring.data.mongodb.database=Skillsync

# Server port
server.port=8080

# Enable MongoDB logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb=INFO

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration