spring.application.name=backend

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://root:root@skillsync.buf804c.mongodb.net/?retryWrites=true&w=majority&appName=Skillsync
spring.data.mongodb.database=Skillsync

# Server port
server.port=8080

# Enable MongoDB logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb=INFO

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

spring.security.oauth2.client.registration.google.client-id=672881030818-i9g7spqih8hc8edub0r3d8jinn29r564.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=Ov23liwj60D40hQuIJXM
spring.security.oauth2.client.registration.github.client-secret=4c09d8e7748195ca6d2ba6021f9e215b719d7e76
spring.security.oauth2.client.registration.github.scope=user:email
