spring.application.name=backend

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://root:root@skillsync.buf804c.mongodb.net/?retryWrites=true&w=majority&appName=Skillsync
spring.data.mongodb.database=Skillsync

# Server port
server.port=8080

# Enable MongoDB logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb=INFO

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Google OAuth Configuration
google.client.id=240003374876-vouemc46ift88d5crhtgmm21nqtio286.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/login/oauth2/code/google
google.auth.uri=https://accounts.google.com/o/oauth2/auth
google.token.uri=https://oauth2.googleapis.com/token
google.auth.provider.x509.cert.url=https://www.googleapis.com/oauth2/v1/certs
